from aiogram_dialog import Dialog

from .windows import (
    broadcast_buttons_window,
    broadcast_confirm_window,
    broadcast_content_window,
    broadcast_options_window,
    menu_window,
    order_force_window,
    order_retry_window,
    orders_menu_window,
    promo_bulk_window,
    promo_create_window,
    promo_details_window,
    promo_menu_window,
    promo_quick_window,
    promo_set_limit_window,
    stars_sell_admin_details_window,
    stars_sell_admin_list_window,
    stars_sell_history_details_window,
    stars_sell_history_window,
    stars_sell_menu_window,
    stars_sell_payment_window,
    stars_sell_stars_window,
    stars_sell_wallet_window,
    stats_window,
    users_add_balance_window,
    users_lookup_window,
    users_menu_window,
)

dialog: Dialog = Dialog(
    menu_window,
    broadcast_content_window,
    broadcast_options_window,
    broadcast_buttons_window,
    broadcast_confirm_window,
    promo_menu_window,
    promo_details_window,
    promo_create_window,
    promo_quick_window,
    promo_bulk_window,
    promo_set_limit_window,
    orders_menu_window,
    order_retry_window,
    order_force_window,
    users_menu_window,
    users_add_balance_window,
    users_lookup_window,
    stars_sell_menu_window,
    stars_sell_stars_window,
    stars_sell_wallet_window,
    stars_sell_payment_window,
    stars_sell_history_window,
    stars_sell_history_details_window,
    stars_sell_admin_list_window,
    stars_sell_admin_details_window,
    stats_window,
)


__all__ = ["dialog"]
