from aiogram.fsm.state import State, StatesGroup


class AdminSG(StatesGroup):
    menu = State()
    broadcast_content = State()
    broadcast_options = State()
    broadcast_buttons = State()
    broadcast_confirm = State()
    promo_menu = State()
    promo_details = State()
    promo_create = State()
    promo_quick = State()
    promo_bulk = State()
    promo_set_limit = State()
    orders_menu = State()
    order_retry = State()
    order_force = State()
    users_menu = State()
    user_add_balance = State()
    user_lookup_contact = State()
    stars_sell_menu = State()
    stars_sell_stars = State()
    stars_sell_wallet = State()
    stars_sell_payment = State()
    stars_sell_history = State()
    stars_sell_history_details = State()
    stars_sell_admin_list = State()
    stars_sell_admin_details = State()
    stats = State()
