from .calculator import calculator_window
from .faq import faq_window
from .gifts import (
    gifts_catalog_window,
    gifts_message_window,
    gifts_payment_window,
    gifts_recipient_window,
    gifts_sender_privacy_window,
)
from .menu import menu_window
from .premium import premium_payment_window, premium_plans_window, premium_recipient_window
from .profile import (
    checks_claim_password_window,
    checks_create_confirm_window,
    checks_create_password_window,
    checks_create_recipient_window,
    checks_create_stars_window,
    checks_details_window,
    checks_edit_password_window,
    checks_edit_recipient_window,
    checks_history_details_window,
    checks_history_window,
    checks_list_window,
    checks_settings_window,
    history_details_window,
    history_window,
    profile_window,
    promo_window,
    referral_details_window,
    referral_list_window,
    referral_window,
    referral_withdraw_window,
)
from .stars import stars_amount_window, stars_payment_window, stars_recipient_window
from .stars_sell import (
    stars_sell_history_details_window,
    stars_sell_history_window,
    stars_sell_menu_window,
    stars_sell_payment_window,
    stars_sell_stars_window,
    stars_sell_wallet_window,
)
from .topup import topup_amount_window, topup_payment_window

__all__ = [
    "checks_create_password_window",
    "checks_create_confirm_window",
    "checks_create_recipient_window",
    "checks_create_stars_window",
    "checks_claim_password_window",
    "checks_details_window",
    "checks_edit_password_window",
    "checks_edit_recipient_window",
    "checks_history_details_window",
    "checks_history_window",
    "checks_list_window",
    "checks_settings_window",
    "calculator_window",
    "faq_window",
    "gifts_catalog_window",
    "gifts_message_window",
    "gifts_payment_window",
    "gifts_recipient_window",
    "gifts_sender_privacy_window",
    "history_details_window",
    "history_window",
    "menu_window",
    "premium_payment_window",
    "premium_plans_window",
    "premium_recipient_window",
    "profile_window",
    "promo_window",
    "referral_details_window",
    "referral_list_window",
    "referral_withdraw_window",
    "referral_window",
    "stars_amount_window",
    "stars_payment_window",
    "stars_recipient_window",
    "stars_sell_history_details_window",
    "stars_sell_history_window",
    "stars_sell_menu_window",
    "stars_sell_payment_window",
    "stars_sell_stars_window",
    "stars_sell_wallet_window",
    "topup_amount_window",
    "topup_payment_window",
]
