from aiogram.enums.button_style import ButtonStyle
from aiogram_dialog import Window
from aiogram_dialog.widgets.input import MessageInput
from aiogram_dialog.widgets.kbd import Button
from aiogram_dialog.widgets.style import Style
from aiogram_dialog.widgets.text import Format

from app.telegram.dialogs.common.premium_emoji import (
    CHECK_EMOJI_ID,
    CLOSE_EMOJI_ID,
    CRYPTOBOT_PAY_EMOJI_ID,
    EDIT_2_EMOJI_ID,
    GIFT_BEAR_WITH_BOUQUET_EMOJI_ID,
    GIFT_BEAR_WITH_HEART_EMOJI_ID,
    GIFT_CLOWN_BEAR_EMOJI_ID,
    GIFT_DEFAULT_BEAR_EMOJI_ID,
    GIFT_EASTER_BEAR_EMOJI_ID,
    GIFT_IRISH_BEAR_EMOJI_ID,
    GIFT_NEW_YEAR_BEAR_EMOJI_ID,
    GIFT_NEW_YEAR_TREE_EMOJI_ID,
    GIFT_VALENTINE_HEART_EMOJI_ID,
    GIFT_WORKER_BEAR_EMOJI_ID,
    HELEKET_PAY_EMOJI_ID,
    LEFT_SQUARE_EMOJI_ID,
    LZT_PAY_EMOJI_ID,
    NICEPAY_EMOJI_ID,
    SPB_PAY_EMOJI_ID,
    TON_EMOJI_ID,
    USER_EMOJI_ID,
    WALLET_EMOJI_ID,
    XROCKET_EMOJI_ID,
)

from ..getters import (
    gifts_catalog_getter,
    gifts_message_getter,
    gifts_payment_getter,
    gifts_recipient_getter,
    gifts_sender_privacy_getter,
)
from ..handlers import (
    buy_gift_for_self,
    handle_gift_message_input,
    handle_gift_recipient_input,
    pay_gift_with_balance,
    pay_gift_with_crypto,
    pay_gift_with_heleket,
    pay_gift_with_lzt,
    pay_gift_with_nicepay_kz,
    pay_gift_with_nicepay_ru,
    pay_gift_with_platega,
    pay_gift_with_ton,
    pay_gift_with_xrocket,
    select_gift_bear_with_bouquet,
    select_gift_bear_with_heart,
    select_gift_clown_bear,
    select_gift_default_bear,
    select_gift_easter_bear,
    select_gift_irish_bear,
    select_gift_new_year_bear,
    select_gift_new_year_tree,
    select_gift_sender_private,
    select_gift_sender_visible,
    select_gift_valentine_heart,
    select_gift_worker_bear,
    show_gifts,
    show_gifts_catalog,
    show_gifts_message,
    show_gifts_sender_privacy,
    show_menu,
    skip_gift_message,
)
from ..ids import (
    STOREFRONT_BACK_TO_MENU_BUTTON_ID,
    STOREFRONT_BUY_FOR_SELF_GIFT_BUTTON_ID,
    STOREFRONT_GIFT_BACK_TO_CATALOG_BUTTON_ID,
    STOREFRONT_GIFT_BACK_TO_MESSAGE_BUTTON_ID,
    STOREFRONT_GIFT_BACK_TO_RECIPIENT_BUTTON_ID,
    STOREFRONT_GIFT_BACK_TO_SENDER_VISIBILITY_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_BEAR_WITH_BOUQUET_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_BEAR_WITH_HEART_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_CLOWN_BEAR_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_DEFAULT_BEAR_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_EASTER_BEAR_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_IRISH_BEAR_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_NEW_YEAR_BEAR_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_NEW_YEAR_TREE_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_VALENTINE_HEART_BUTTON_ID,
    STOREFRONT_GIFT_SELECT_WORKER_BEAR_BUTTON_ID,
    STOREFRONT_GIFT_SENDER_PRIVATE_BUTTON_ID,
    STOREFRONT_GIFT_SENDER_VISIBLE_BUTTON_ID,
    STOREFRONT_GIFT_SKIP_MESSAGE_BUTTON_ID,
    STOREFRONT_PAY_GIFT_BALANCE_BUTTON_ID,
    STOREFRONT_PAY_GIFT_CRYPTO_BUTTON_ID,
    STOREFRONT_PAY_GIFT_CRYPTO_DANGER_BUTTON_ID,
    STOREFRONT_PAY_GIFT_HELEKET_BUTTON_ID,
    STOREFRONT_PAY_GIFT_HELEKET_DANGER_BUTTON_ID,
    STOREFRONT_PAY_GIFT_LZT_BUTTON_ID,
    STOREFRONT_PAY_GIFT_LZT_DANGER_BUTTON_ID,
    STOREFRONT_PAY_GIFT_NICEPAY_KZ_BUTTON_ID,
    STOREFRONT_PAY_GIFT_NICEPAY_KZ_DANGER_BUTTON_ID,
    STOREFRONT_PAY_GIFT_NICEPAY_RU_BUTTON_ID,
    STOREFRONT_PAY_GIFT_NICEPAY_RU_DANGER_BUTTON_ID,
    STOREFRONT_PAY_GIFT_PLATEGA_BUTTON_ID,
    STOREFRONT_PAY_GIFT_PLATEGA_DANGER_BUTTON_ID,
    STOREFRONT_PAY_GIFT_TON_BUTTON_ID,
    STOREFRONT_PAY_GIFT_TON_DANGER_BUTTON_ID,
    STOREFRONT_PAY_GIFT_XROCKET_BUTTON_ID,
    STOREFRONT_PAY_GIFT_XROCKET_DANGER_BUTTON_ID,
)
from ..states import StorefrontSG
from .common import banner_preview

gifts_recipient_window: Window = Window(
    banner_preview(),
    Format("{text}"),
    MessageInput(handle_gift_recipient_input),
    Button(
        Format("{buy_for_self_text}"),
        id=STOREFRONT_BUY_FOR_SELF_GIFT_BUTTON_ID,
        on_click=buy_gift_for_self,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=USER_EMOJI_ID),
    ),
    Button(
        Format("{back_button_text}"),
        id=STOREFRONT_BACK_TO_MENU_BUTTON_ID,
        on_click=show_menu,
        style=Style(emoji_id=LEFT_SQUARE_EMOJI_ID),
    ),
    state=StorefrontSG.gifts_recipient,
    getter=gifts_recipient_getter,
)

gifts_catalog_window: Window = Window(
    banner_preview(),
    Format("{text}"),
    Button(
        Format("{gift_new_year_tree_text}"),
        id=STOREFRONT_GIFT_SELECT_NEW_YEAR_TREE_BUTTON_ID,
        on_click=select_gift_new_year_tree,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_NEW_YEAR_TREE_EMOJI_ID),
    ),
    Button(
        Format("{gift_valentine_heart_text}"),
        id=STOREFRONT_GIFT_SELECT_VALENTINE_HEART_BUTTON_ID,
        on_click=select_gift_valentine_heart,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_VALENTINE_HEART_EMOJI_ID),
    ),
    Button(
        Format("{gift_new_year_bear_text}"),
        id=STOREFRONT_GIFT_SELECT_NEW_YEAR_BEAR_BUTTON_ID,
        on_click=select_gift_new_year_bear,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_NEW_YEAR_BEAR_EMOJI_ID),
    ),
    Button(
        Format("{gift_bear_with_heart_text}"),
        id=STOREFRONT_GIFT_SELECT_BEAR_WITH_HEART_BUTTON_ID,
        on_click=select_gift_bear_with_heart,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_BEAR_WITH_HEART_EMOJI_ID),
    ),
    Button(
        Format("{gift_bear_with_bouquet_text}"),
        id=STOREFRONT_GIFT_SELECT_BEAR_WITH_BOUQUET_BUTTON_ID,
        on_click=select_gift_bear_with_bouquet,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_BEAR_WITH_BOUQUET_EMOJI_ID),
    ),
    Button(
        Format("{gift_irish_bear_text}"),
        id=STOREFRONT_GIFT_SELECT_IRISH_BEAR_BUTTON_ID,
        on_click=select_gift_irish_bear,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_IRISH_BEAR_EMOJI_ID),
    ),
    Button(
        Format("{gift_clown_bear_text}"),
        id=STOREFRONT_GIFT_SELECT_CLOWN_BEAR_BUTTON_ID,
        on_click=select_gift_clown_bear,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_CLOWN_BEAR_EMOJI_ID),
    ),
    Button(
        Format("{gift_easter_bear_text}"),
        id=STOREFRONT_GIFT_SELECT_EASTER_BEAR_BUTTON_ID,
        on_click=select_gift_easter_bear,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_EASTER_BEAR_EMOJI_ID),
    ),
    Button(
        Format("{gift_worker_bear_text}"),
        id=STOREFRONT_GIFT_SELECT_WORKER_BEAR_BUTTON_ID,
        on_click=select_gift_worker_bear,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_WORKER_BEAR_EMOJI_ID),
    ),
    Button(
        Format("{gift_default_bear_text}"),
        id=STOREFRONT_GIFT_SELECT_DEFAULT_BEAR_BUTTON_ID,
        on_click=select_gift_default_bear,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=GIFT_DEFAULT_BEAR_EMOJI_ID),
    ),
    Button(
        Format("{back_recipient_text}"),
        id=STOREFRONT_GIFT_BACK_TO_RECIPIENT_BUTTON_ID,
        on_click=show_gifts,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_button_text}"),
        id=STOREFRONT_BACK_TO_MENU_BUTTON_ID,
        on_click=show_menu,
        style=Style(emoji_id=LEFT_SQUARE_EMOJI_ID),
    ),
    state=StorefrontSG.gifts_catalog,
    getter=gifts_catalog_getter,
)

gifts_message_window: Window = Window(
    banner_preview(),
    Format("{text}"),
    MessageInput(handle_gift_message_input),
    Button(
        Format("{skip_message_text}"),
        id=STOREFRONT_GIFT_SKIP_MESSAGE_BUTTON_ID,
        on_click=skip_gift_message,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=CHECK_EMOJI_ID),
    ),
    Button(
        Format("{back_recipient_text}"),
        id=STOREFRONT_GIFT_BACK_TO_RECIPIENT_BUTTON_ID,
        on_click=show_gifts,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_catalog_text}"),
        id=STOREFRONT_GIFT_BACK_TO_CATALOG_BUTTON_ID,
        on_click=show_gifts_catalog,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_button_text}"),
        id=STOREFRONT_BACK_TO_MENU_BUTTON_ID,
        on_click=show_menu,
        style=Style(emoji_id=LEFT_SQUARE_EMOJI_ID),
    ),
    state=StorefrontSG.gifts_message,
    getter=gifts_message_getter,
)

gifts_sender_privacy_window: Window = Window(
    banner_preview(),
    Format("{text}"),
    Button(
        Format("{sender_visible_text}"),
        id=STOREFRONT_GIFT_SENDER_VISIBLE_BUTTON_ID,
        on_click=select_gift_sender_visible,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=CHECK_EMOJI_ID),
    ),
    Button(
        Format("{sender_private_text}"),
        id=STOREFRONT_GIFT_SENDER_PRIVATE_BUTTON_ID,
        on_click=select_gift_sender_private,
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=CLOSE_EMOJI_ID),
    ),
    Button(
        Format("{back_recipient_text}"),
        id=STOREFRONT_GIFT_BACK_TO_RECIPIENT_BUTTON_ID,
        on_click=show_gifts,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_catalog_text}"),
        id=STOREFRONT_GIFT_BACK_TO_CATALOG_BUTTON_ID,
        on_click=show_gifts_catalog,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_message_text}"),
        id=STOREFRONT_GIFT_BACK_TO_MESSAGE_BUTTON_ID,
        on_click=show_gifts_message,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_button_text}"),
        id=STOREFRONT_BACK_TO_MENU_BUTTON_ID,
        on_click=show_menu,
        style=Style(emoji_id=LEFT_SQUARE_EMOJI_ID),
    ),
    state=StorefrontSG.gifts_sender_privacy,
    getter=gifts_sender_privacy_getter,
)

gifts_payment_window: Window = Window(
    banner_preview(),
    Format("{text}"),
    Button(
        Format("{pay_crypto_text}"),
        id=STOREFRONT_PAY_GIFT_CRYPTO_BUTTON_ID,
        on_click=pay_gift_with_crypto,
        when="can_pay_crypto_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=CRYPTOBOT_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_crypto_text}"),
        id=STOREFRONT_PAY_GIFT_CRYPTO_DANGER_BUTTON_ID,
        on_click=pay_gift_with_crypto,
        when="can_pay_crypto_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=CRYPTOBOT_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_ton_text}"),
        id=STOREFRONT_PAY_GIFT_TON_BUTTON_ID,
        on_click=pay_gift_with_ton,
        when="can_pay_ton_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=TON_EMOJI_ID),
    ),
    Button(
        Format("{pay_ton_text}"),
        id=STOREFRONT_PAY_GIFT_TON_DANGER_BUTTON_ID,
        on_click=pay_gift_with_ton,
        when="can_pay_ton_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=TON_EMOJI_ID),
    ),
    Button(
        Format("{pay_platega_text}"),
        id=STOREFRONT_PAY_GIFT_PLATEGA_BUTTON_ID,
        on_click=pay_gift_with_platega,
        when="can_pay_platega_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=SPB_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_platega_text}"),
        id=STOREFRONT_PAY_GIFT_PLATEGA_DANGER_BUTTON_ID,
        on_click=pay_gift_with_platega,
        when="can_pay_platega_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=SPB_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_lzt_text}"),
        id=STOREFRONT_PAY_GIFT_LZT_BUTTON_ID,
        on_click=pay_gift_with_lzt,
        when="can_pay_lzt_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=LZT_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_lzt_text}"),
        id=STOREFRONT_PAY_GIFT_LZT_DANGER_BUTTON_ID,
        on_click=pay_gift_with_lzt,
        when="can_pay_lzt_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=LZT_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_nicepay_ru_text}"),
        id=STOREFRONT_PAY_GIFT_NICEPAY_RU_BUTTON_ID,
        on_click=pay_gift_with_nicepay_ru,
        when="can_pay_nicepay_ru_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=NICEPAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_nicepay_ru_text}"),
        id=STOREFRONT_PAY_GIFT_NICEPAY_RU_DANGER_BUTTON_ID,
        on_click=pay_gift_with_nicepay_ru,
        when="can_pay_nicepay_ru_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=NICEPAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_nicepay_kz_text}"),
        id=STOREFRONT_PAY_GIFT_NICEPAY_KZ_BUTTON_ID,
        on_click=pay_gift_with_nicepay_kz,
        when="can_pay_nicepay_kz_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=NICEPAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_nicepay_kz_text}"),
        id=STOREFRONT_PAY_GIFT_NICEPAY_KZ_DANGER_BUTTON_ID,
        on_click=pay_gift_with_nicepay_kz,
        when="can_pay_nicepay_kz_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=NICEPAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_heleket_text}"),
        id=STOREFRONT_PAY_GIFT_HELEKET_BUTTON_ID,
        on_click=pay_gift_with_heleket,
        when="can_pay_heleket_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=HELEKET_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_heleket_text}"),
        id=STOREFRONT_PAY_GIFT_HELEKET_DANGER_BUTTON_ID,
        on_click=pay_gift_with_heleket,
        when="can_pay_heleket_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=HELEKET_PAY_EMOJI_ID),
    ),
    Button(
        Format("{pay_xrocket_text}"),
        id=STOREFRONT_PAY_GIFT_XROCKET_BUTTON_ID,
        on_click=pay_gift_with_xrocket,
        when="can_pay_xrocket_primary",
        style=Style(style=ButtonStyle.PRIMARY, emoji_id=XROCKET_EMOJI_ID),
    ),
    Button(
        Format("{pay_xrocket_text}"),
        id=STOREFRONT_PAY_GIFT_XROCKET_DANGER_BUTTON_ID,
        on_click=pay_gift_with_xrocket,
        when="can_pay_xrocket_danger",
        style=Style(style=ButtonStyle.DANGER, emoji_id=XROCKET_EMOJI_ID),
    ),
    Button(
        Format("{pay_balance_text}"),
        id=STOREFRONT_PAY_GIFT_BALANCE_BUTTON_ID,
        on_click=pay_gift_with_balance,
        when="can_pay_balance",
        style=Style(style=ButtonStyle.SUCCESS, emoji_id=WALLET_EMOJI_ID),
    ),
    Button(
        Format("{back_recipient_text}"),
        id=STOREFRONT_GIFT_BACK_TO_RECIPIENT_BUTTON_ID,
        on_click=show_gifts,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_catalog_text}"),
        id=STOREFRONT_GIFT_BACK_TO_CATALOG_BUTTON_ID,
        on_click=show_gifts_catalog,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_message_text}"),
        id=STOREFRONT_GIFT_BACK_TO_MESSAGE_BUTTON_ID,
        on_click=show_gifts_message,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_sender_visibility_text}"),
        id=STOREFRONT_GIFT_BACK_TO_SENDER_VISIBILITY_BUTTON_ID,
        on_click=show_gifts_sender_privacy,
        style=Style(emoji_id=EDIT_2_EMOJI_ID),
    ),
    Button(
        Format("{back_button_text}"),
        id=STOREFRONT_BACK_TO_MENU_BUTTON_ID,
        on_click=show_menu,
        style=Style(emoji_id=LEFT_SQUARE_EMOJI_ID),
    ),
    state=StorefrontSG.gifts_payment,
    getter=gifts_payment_getter,
)
