from typing import Final

STOREFRONT_OPEN_STARS_BUTTON_ID: Final[str] = "storefront_open_stars"
STOREFRONT_OPEN_MINIAPP_BUTTON_ID: Final[str] = "storefront_open_miniapp"
STOREFRONT_OPEN_PREMIUM_BUTTON_ID: Final[str] = "storefront_open_premium"
STOREFRONT_OPEN_STARS_SELL_BUTTON_ID: Final[str] = "storefront_open_stars_sell"
STOREFRONT_OPEN_GIFTS_BUTTON_ID: Final[str] = "storefront_open_gifts"
STOREFRONT_OPEN_TOPUP_BUTTON_ID: Final[str] = "storefront_open_topup"
STOREFRONT_OPEN_CALCULATOR_BUTTON_ID: Final[str] = "storefront_open_calculator"
STOREFRONT_OPEN_PROFILE_BUTTON_ID: Final[str] = "storefront_open_profile"
STOREFRONT_OPEN_FAQ_BUTTON_ID: Final[str] = "storefront_open_faq"
STOREFRONT_BACK_TO_MENU_BUTTON_ID: Final[str] = "storefront_back_to_menu"
STOREFRONT_BACK_TO_STARS_AMOUNT_BUTTON_ID: Final[str] = "storefront_back_to_stars_amount"
STOREFRONT_BACK_TO_PREMIUM_PLANS_BUTTON_ID: Final[str] = "storefront_back_to_premium_plans"
STOREFRONT_CHANGE_RECIPIENT_BUTTON_ID: Final[str] = "storefront_change_recipient"
STOREFRONT_CHANGE_PREMIUM_RECIPIENT_BUTTON_ID: Final[str] = "storefront_change_premium_recipient"
STOREFRONT_BUY_FOR_SELF_BUTTON_ID: Final[str] = "storefront_buy_for_self"
STOREFRONT_BUY_FOR_SELF_PREMIUM_BUTTON_ID: Final[str] = "storefront_buy_for_self_premium"
STOREFRONT_PAY_CRYPTO_BUTTON_ID: Final[str] = "storefront_pay_crypto"
STOREFRONT_PAY_TON_BUTTON_ID: Final[str] = "storefront_pay_ton"
STOREFRONT_PAY_PLATEGA_BUTTON_ID: Final[str] = "storefront_pay_platega"
STOREFRONT_PAY_LZT_BUTTON_ID: Final[str] = "storefront_pay_lzt"
STOREFRONT_PAY_NICEPAY_RU_BUTTON_ID: Final[str] = "storefront_pay_nicepay_ru"
STOREFRONT_PAY_NICEPAY_KZ_BUTTON_ID: Final[str] = "storefront_pay_nicepay_kz"
STOREFRONT_PAY_XROCKET_BUTTON_ID: Final[str] = "storefront_pay_xrocket"
STOREFRONT_PAY_HELEKET_BUTTON_ID: Final[str] = "storefront_pay_heleket"
STOREFRONT_PAY_CRYPTO_DANGER_BUTTON_ID: Final[str] = "storefront_pay_crypto_danger"
STOREFRONT_PAY_TON_DANGER_BUTTON_ID: Final[str] = "storefront_pay_ton_danger"
STOREFRONT_PAY_PLATEGA_DANGER_BUTTON_ID: Final[str] = "storefront_pay_platega_danger"
STOREFRONT_PAY_LZT_DANGER_BUTTON_ID: Final[str] = "storefront_pay_lzt_danger"
STOREFRONT_PAY_NICEPAY_RU_DANGER_BUTTON_ID: Final[str] = "storefront_pay_nicepay_ru_danger"
STOREFRONT_PAY_NICEPAY_KZ_DANGER_BUTTON_ID: Final[str] = "storefront_pay_nicepay_kz_danger"
STOREFRONT_PAY_XROCKET_DANGER_BUTTON_ID: Final[str] = "storefront_pay_xrocket_danger"
STOREFRONT_PAY_HELEKET_DANGER_BUTTON_ID: Final[str] = "storefront_pay_heleket_danger"
STOREFRONT_PAY_BALANCE_BUTTON_ID: Final[str] = "storefront_pay_balance"
STOREFRONT_PAY_PREMIUM_CRYPTO_BUTTON_ID: Final[str] = "storefront_pay_premium_crypto"
STOREFRONT_PAY_PREMIUM_TON_BUTTON_ID: Final[str] = "storefront_pay_premium_ton"
STOREFRONT_PAY_PREMIUM_PLATEGA_BUTTON_ID: Final[str] = "storefront_pay_premium_platega"
STOREFRONT_PAY_PREMIUM_LZT_BUTTON_ID: Final[str] = "storefront_pay_premium_lzt"
STOREFRONT_PAY_PREMIUM_NICEPAY_RU_BUTTON_ID: Final[str] = "storefront_pay_premium_nicepay_ru"
STOREFRONT_PAY_PREMIUM_NICEPAY_KZ_BUTTON_ID: Final[str] = "storefront_pay_premium_nicepay_kz"
STOREFRONT_PAY_PREMIUM_XROCKET_BUTTON_ID: Final[str] = "storefront_pay_premium_xrocket"
STOREFRONT_PAY_PREMIUM_HELEKET_BUTTON_ID: Final[str] = "storefront_pay_premium_heleket"
STOREFRONT_PAY_PREMIUM_CRYPTO_DANGER_BUTTON_ID: Final[str] = "storefront_pay_premium_crypto_danger"
STOREFRONT_PAY_PREMIUM_TON_DANGER_BUTTON_ID: Final[str] = "storefront_pay_premium_ton_danger"
STOREFRONT_PAY_PREMIUM_PLATEGA_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_premium_platega_danger"
)
STOREFRONT_PAY_PREMIUM_LZT_DANGER_BUTTON_ID: Final[str] = "storefront_pay_premium_lzt_danger"
STOREFRONT_PAY_PREMIUM_NICEPAY_RU_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_premium_nicepay_ru_danger"
)
STOREFRONT_PAY_PREMIUM_NICEPAY_KZ_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_premium_nicepay_kz_danger"
)
STOREFRONT_PAY_PREMIUM_XROCKET_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_premium_xrocket_danger"
)
STOREFRONT_PAY_PREMIUM_HELEKET_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_premium_heleket_danger"
)
STOREFRONT_PAY_PREMIUM_BALANCE_BUTTON_ID: Final[str] = "storefront_pay_premium_balance"
STOREFRONT_PAY_TOPUP_CRYPTO_BUTTON_ID: Final[str] = "storefront_pay_topup_crypto"
STOREFRONT_PAY_TOPUP_TON_BUTTON_ID: Final[str] = "storefront_pay_topup_ton"
STOREFRONT_PAY_TOPUP_PLATEGA_BUTTON_ID: Final[str] = "storefront_pay_topup_platega"
STOREFRONT_PAY_TOPUP_LZT_BUTTON_ID: Final[str] = "storefront_pay_topup_lzt"
STOREFRONT_PAY_TOPUP_NICEPAY_RU_BUTTON_ID: Final[str] = "storefront_pay_topup_nicepay_ru"
STOREFRONT_PAY_TOPUP_NICEPAY_KZ_BUTTON_ID: Final[str] = "storefront_pay_topup_nicepay_kz"
STOREFRONT_PAY_TOPUP_XROCKET_BUTTON_ID: Final[str] = "storefront_pay_topup_xrocket"
STOREFRONT_PAY_TOPUP_HELEKET_BUTTON_ID: Final[str] = "storefront_pay_topup_heleket"
STOREFRONT_PAY_TOPUP_CRYPTO_DANGER_BUTTON_ID: Final[str] = "storefront_pay_topup_crypto_danger"
STOREFRONT_PAY_TOPUP_TON_DANGER_BUTTON_ID: Final[str] = "storefront_pay_topup_ton_danger"
STOREFRONT_PAY_TOPUP_PLATEGA_DANGER_BUTTON_ID: Final[str] = "storefront_pay_topup_platega_danger"
STOREFRONT_PAY_TOPUP_LZT_DANGER_BUTTON_ID: Final[str] = "storefront_pay_topup_lzt_danger"
STOREFRONT_PAY_TOPUP_NICEPAY_RU_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_topup_nicepay_ru_danger"
)
STOREFRONT_PAY_TOPUP_NICEPAY_KZ_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_topup_nicepay_kz_danger"
)
STOREFRONT_PAY_TOPUP_XROCKET_DANGER_BUTTON_ID: Final[str] = "storefront_pay_topup_xrocket_danger"
STOREFRONT_PAY_TOPUP_HELEKET_DANGER_BUTTON_ID: Final[str] = "storefront_pay_topup_heleket_danger"
STOREFRONT_BUY_FOR_SELF_GIFT_BUTTON_ID: Final[str] = "storefront_buy_for_self_gift"
STOREFRONT_GIFT_SELECT_NEW_YEAR_TREE_BUTTON_ID: Final[str] = "storefront_gift_select_ny_tree"
STOREFRONT_GIFT_SELECT_VALENTINE_HEART_BUTTON_ID: Final[str] = "storefront_gift_select_v_heart"
STOREFRONT_GIFT_SELECT_NEW_YEAR_BEAR_BUTTON_ID: Final[str] = "storefront_gift_select_ny_bear"
STOREFRONT_GIFT_SELECT_BEAR_WITH_HEART_BUTTON_ID: Final[str] = "storefront_gift_select_bear_heart"
STOREFRONT_GIFT_SELECT_BEAR_WITH_BOUQUET_BUTTON_ID: Final[str] = (
    "storefront_gift_select_bear_bouquet"
)
STOREFRONT_GIFT_SELECT_IRISH_BEAR_BUTTON_ID: Final[str] = "storefront_gift_select_irish_bear"
STOREFRONT_GIFT_SELECT_CLOWN_BEAR_BUTTON_ID: Final[str] = "storefront_gift_select_clown_bear"
STOREFRONT_GIFT_SELECT_EASTER_BEAR_BUTTON_ID: Final[str] = "storefront_gift_select_easter_bear"
STOREFRONT_GIFT_SELECT_WORKER_BEAR_BUTTON_ID: Final[str] = "storefront_gift_select_worker_bear"
STOREFRONT_GIFT_SELECT_DEFAULT_BEAR_BUTTON_ID: Final[str] = "storefront_gift_select_default_bear"
STOREFRONT_GIFT_BACK_TO_RECIPIENT_BUTTON_ID: Final[str] = "storefront_gift_back_to_recipient"
STOREFRONT_GIFT_BACK_TO_CATALOG_BUTTON_ID: Final[str] = "storefront_gift_back_to_catalog"
STOREFRONT_GIFT_SKIP_MESSAGE_BUTTON_ID: Final[str] = "storefront_gift_skip_message"
STOREFRONT_GIFT_SENDER_VISIBLE_BUTTON_ID: Final[str] = "storefront_gift_sender_visible"
STOREFRONT_GIFT_SENDER_PRIVATE_BUTTON_ID: Final[str] = "storefront_gift_sender_private"
STOREFRONT_GIFT_BACK_TO_MESSAGE_BUTTON_ID: Final[str] = "storefront_gift_back_to_message"
STOREFRONT_GIFT_BACK_TO_SENDER_VISIBILITY_BUTTON_ID: Final[str] = (
    "storefront_gift_back_to_sender_visibility"
)
STOREFRONT_PAY_GIFT_CRYPTO_BUTTON_ID: Final[str] = "storefront_pay_gift_crypto"
STOREFRONT_PAY_GIFT_TON_BUTTON_ID: Final[str] = "storefront_pay_gift_ton"
STOREFRONT_PAY_GIFT_PLATEGA_BUTTON_ID: Final[str] = "storefront_pay_gift_platega"
STOREFRONT_PAY_GIFT_LZT_BUTTON_ID: Final[str] = "storefront_pay_gift_lzt"
STOREFRONT_PAY_GIFT_NICEPAY_RU_BUTTON_ID: Final[str] = "storefront_pay_gift_nicepay_ru"
STOREFRONT_PAY_GIFT_NICEPAY_KZ_BUTTON_ID: Final[str] = "storefront_pay_gift_nicepay_kz"
STOREFRONT_PAY_GIFT_XROCKET_BUTTON_ID: Final[str] = "storefront_pay_gift_xrocket"
STOREFRONT_PAY_GIFT_HELEKET_BUTTON_ID: Final[str] = "storefront_pay_gift_heleket"
STOREFRONT_PAY_GIFT_CRYPTO_DANGER_BUTTON_ID: Final[str] = "storefront_pay_gift_crypto_danger"
STOREFRONT_PAY_GIFT_TON_DANGER_BUTTON_ID: Final[str] = "storefront_pay_gift_ton_danger"
STOREFRONT_PAY_GIFT_PLATEGA_DANGER_BUTTON_ID: Final[str] = "storefront_pay_gift_platega_danger"
STOREFRONT_PAY_GIFT_LZT_DANGER_BUTTON_ID: Final[str] = "storefront_pay_gift_lzt_danger"
STOREFRONT_PAY_GIFT_NICEPAY_RU_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_gift_nicepay_ru_danger"
)
STOREFRONT_PAY_GIFT_NICEPAY_KZ_DANGER_BUTTON_ID: Final[str] = (
    "storefront_pay_gift_nicepay_kz_danger"
)
STOREFRONT_PAY_GIFT_XROCKET_DANGER_BUTTON_ID: Final[str] = "storefront_pay_gift_xrocket_danger"
STOREFRONT_PAY_GIFT_HELEKET_DANGER_BUTTON_ID: Final[str] = "storefront_pay_gift_heleket_danger"
STOREFRONT_PAY_GIFT_BALANCE_BUTTON_ID: Final[str] = "storefront_pay_gift_balance"
STOREFRONT_OPEN_REFERRALS_BUTTON_ID: Final[str] = "storefront_open_referrals"
STOREFRONT_OPEN_REFERRALS_LIST_BUTTON_ID: Final[str] = "storefront_open_referrals_list"
STOREFRONT_WITHDRAW_REFERRAL_BALANCE_BUTTON_ID: Final[str] = "storefront_withdraw_ref_balance"
STOREFRONT_OPEN_CHECKS_BUTTON_ID: Final[str] = "storefront_open_checks"
STOREFRONT_OPEN_HISTORY_BUTTON_ID: Final[str] = "sh"
STOREFRONT_HISTORY_SELECT_ORDER_ID: Final[str] = "hsel"
STOREFRONT_HISTORY_PREV_BUTTON_ID: Final[str] = "hpr"
STOREFRONT_HISTORY_PAGE_BUTTON_ID: Final[str] = "hpg"
STOREFRONT_HISTORY_NEXT_BUTTON_ID: Final[str] = "hnx"
STOREFRONT_HISTORY_BACK_TO_LIST_BUTTON_ID: Final[str] = "hbk"
STOREFRONT_STARS_SELL_CREATE_REQUEST_BUTTON_ID: Final[str] = "ss_create"
STOREFRONT_STARS_SELL_HISTORY_BUTTON_ID: Final[str] = "ss_history"
STOREFRONT_STARS_SELL_SEND_INVOICE_BUTTON_ID: Final[str] = "ss_send_invoice"
STOREFRONT_STARS_SELL_CHANGE_STARS_BUTTON_ID: Final[str] = "ss_change_stars"
STOREFRONT_STARS_SELL_CHANGE_WALLET_BUTTON_ID: Final[str] = "ss_change_wallet"
STOREFRONT_STARS_SELL_HISTORY_SELECT_ID: Final[str] = "ss_hsel"
STOREFRONT_STARS_SELL_HISTORY_PREV_BUTTON_ID: Final[str] = "ss_hpr"
STOREFRONT_STARS_SELL_HISTORY_PAGE_BUTTON_ID: Final[str] = "ss_hpg"
STOREFRONT_STARS_SELL_HISTORY_NEXT_BUTTON_ID: Final[str] = "ss_hnx"
STOREFRONT_STARS_SELL_HISTORY_BACK_TO_LIST_BUTTON_ID: Final[str] = "ss_hbk"
STOREFRONT_CHECK_SELECT_ID: Final[str] = "csel"
STOREFRONT_CHECKS_PREV_BUTTON_ID: Final[str] = "cpr"
STOREFRONT_CHECKS_PAGE_BUTTON_ID: Final[str] = "cpg"
STOREFRONT_CHECKS_NEXT_BUTTON_ID: Final[str] = "cnx"
STOREFRONT_CHECKS_HISTORY_OPEN_BUTTON_ID: Final[str] = "chop"
STOREFRONT_CHECKS_HISTORY_SELECT_ID: Final[str] = "chsel"
STOREFRONT_CHECKS_HISTORY_PREV_BUTTON_ID: Final[str] = "chpr"
STOREFRONT_CHECKS_HISTORY_PAGE_BUTTON_ID: Final[str] = "chpg"
STOREFRONT_CHECKS_HISTORY_NEXT_BUTTON_ID: Final[str] = "chnx"
STOREFRONT_CHECKS_HISTORY_BACK_TO_LIST_BUTTON_ID: Final[str] = "chbk"
STOREFRONT_CHECK_BACK_TO_LIST_BUTTON_ID: Final[str] = "cbk"
STOREFRONT_CREATE_STARS_CHECK_BUTTON_ID: Final[str] = "storefront_create_stars_check"
STOREFRONT_CHECK_CREATE_FROM_CHAT_ID: Final[str] = "storefront_check_create_from_chat"
STOREFRONT_CHECK_SHARE_URL_ID: Final[str] = "storefront_check_share_inline"
STOREFRONT_CHECK_CLOSE_BUTTON_ID: Final[str] = "storefront_check_close"
STOREFRONT_CHECK_SETTINGS_BUTTON_ID: Final[str] = "storefront_check_settings"
STOREFRONT_CHECK_SETTINGS_EDIT_RECIPIENT_ID: Final[str] = (
    "storefront_check_settings_edit_recipient"
)
STOREFRONT_CHECK_SETTINGS_EDIT_PASSWORD_ID: Final[str] = "storefront_check_settings_edit_password"
STOREFRONT_CHECK_SETTINGS_CLEAR_RECIPIENT_ID: Final[str] = (
    "storefront_check_settings_clear_recipient"
)
STOREFRONT_CHECK_SETTINGS_CLEAR_PASSWORD_ID: Final[str] = (
    "storefront_check_settings_clear_password"
)
STOREFRONT_CHECK_SETTINGS_BACK_ID: Final[str] = "storefront_check_settings_back"
STOREFRONT_CHECK_CREATE_SKIP_RECIPIENT_ID: Final[str] = "storefront_check_create_skip_recipient"
STOREFRONT_CHECK_CREATE_SKIP_PASSWORD_ID: Final[str] = "storefront_check_create_skip_password"
STOREFRONT_CHECK_CREATE_CONFIRM_ID: Final[str] = "storefront_check_create_confirm"
STOREFRONT_CHECK_CREATE_CHANGE_AMOUNT_ID: Final[str] = "storefront_check_create_change_amount"
STOREFRONT_CHECK_CREATE_CHANGE_RECIPIENT_ID: Final[str] = (
    "storefront_check_create_change_recipient"
)
STOREFRONT_CHECK_CREATE_CHANGE_PASSWORD_ID: Final[str] = "storefront_check_create_change_password"
STOREFRONT_CHECKS_EDIT_BACK_ID: Final[str] = "storefront_checks_edit_back"
STOREFRONT_CHECK_CLAIM_PASSWORD_CANCEL_ID: Final[str] = "storefront_check_claim_password_cancel"
STOREFRONT_REFERRAL_SELECT_USER_ID: Final[str] = "rsel"
STOREFRONT_REFERRAL_PREV_BUTTON_ID: Final[str] = "rpr"
STOREFRONT_REFERRAL_PAGE_BUTTON_ID: Final[str] = "rpg"
STOREFRONT_REFERRAL_NEXT_BUTTON_ID: Final[str] = "rnx"
STOREFRONT_REFERRAL_BACK_TO_LIST_BUTTON_ID: Final[str] = "rbk"
STOREFRONT_OPEN_PROMO_BUTTON_ID: Final[str] = "storefront_open_promo"
STOREFRONT_SELECT_PREMIUM_3_BUTTON_ID: Final[str] = "storefront_select_premium_3"
STOREFRONT_SELECT_PREMIUM_6_BUTTON_ID: Final[str] = "storefront_select_premium_6"
STOREFRONT_SELECT_PREMIUM_12_BUTTON_ID: Final[str] = "storefront_select_premium_12"
STOREFRONT_FAQ_WEBSITE_URL_ID: Final[str] = "storefront_faq_website_url"
STOREFRONT_FAQ_SUPPORT_URL_ID: Final[str] = "storefront_faq_support_url"
STOREFRONT_FAQ_NEWS_URL_ID: Final[str] = "storefront_faq_news_url"
STOREFRONT_FAQ_PRIVACY_WEBAPP_ID: Final[str] = "storefront_faq_privacy_webapp"
STOREFRONT_FAQ_TERMS_WEBAPP_ID: Final[str] = "storefront_faq_terms_webapp"
