from aiogram.fsm.state import State, StatesGroup


class StorefrontSG(StatesGroup):
    menu = State()
    stars_sell_menu = State()
    stars_sell_stars = State()
    stars_sell_wallet = State()
    stars_sell_payment = State()
    stars_sell_history = State()
    stars_sell_history_details = State()
    stars_amount = State()
    stars_recipient = State()
    stars_payment = State()
    premium_plans = State()
    premium_recipient = State()
    premium_payment = State()
    gifts_recipient = State()
    gifts_catalog = State()
    gifts_message = State()
    gifts_sender_privacy = State()
    gifts_payment = State()
    topup_amount = State()
    topup_payment = State()
    calculator = State()
    profile = State()
    checks_list = State()
    checks_details = State()
    checks_history = State()
    checks_history_details = State()
    checks_create_stars = State()
    checks_create_recipient = State()
    checks_create_password = State()
    checks_create_confirm = State()
    checks_settings = State()
    checks_edit_recipient = State()
    checks_edit_password = State()
    checks_claim_password = State()
    referrals = State()
    referrals_withdraw = State()
    referrals_list = State()
    referrals_details = State()
    history = State()
    history_details = State()
    promo = State()
    faq = State()
